# ============================================================
# PMSM Winding Assignment Script (8p/12s)
# source=canonical, k_w=0.8660
# Auto-generated by pmsm_winding_builder.py v2
# ============================================================

import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop = ScriptEnv.GetDesktop()
oProject = oDesktop.GetActiveProject()
oDesign = oProject.SetActiveDesign("Motor_Design")
oModule = oDesign.GetModule("BoundarySetup")

# Step 1: 定义三相绕组 (Winding)
oModule.AssignWindingGroup(
    [
        "NAME:WindingA",
        "Type:=", "Current",
        "IsSolid:=", False,
        "Current:=", "0A",
        "Resistance:=", "0.1ohm",
        "Inductance:=", "0.001H",
        "Voltage:=", "0V",
        "ParallelBranchesNum:=", "1"
    ]
)

oModule.AssignWindingGroup(
    [
        "NAME:WindingB",
        "Type:=", "Current",
        "IsSolid:=", False,
        "Current:=", "0A",
        "Resistance:=", "0.1ohm",
        "Inductance:=", "0.001H",
        "Voltage:=", "0V",
        "ParallelBranchesNum:=", "1"
    ]
)

oModule.AssignWindingGroup(
    [
        "NAME:WindingC",
        "Type:=", "Current",
        "IsSolid:=", False,
        "Current:=", "0A",
        "Resistance:=", "0.1ohm",
        "Inductance:=", "0.001H",
        "Voltage:=", "0V",
        "ParallelBranchesNum:=", "1"
    ]
)

# Step 2: 定义 Coil Group (按 phase + polarity)
# 约定 (standard):
#   A+/B+/C+ → PolarityType=Positive
#   A-/B-/C- → PolarityType=Negative
oModule.AssignCoilGroup(
    [
        "NAME:A+",
        "Objects:=", ["Coil_1", "Coil_7"],
        "Conductor number:=", "40",
        "PolarityType:=", "Positive"
    ]
)

oModule.AssignCoilGroup(
    [
        "NAME:A-",
        "Objects:=", ["Coil_2", "Coil_8"],
        "Conductor number:=", "40",
        "PolarityType:=", "Negative"
    ]
)

oModule.AssignCoilGroup(
    [
        "NAME:B+",
        "Objects:=", ["Coil_3", "Coil_9"],
        "Conductor number:=", "40",
        "PolarityType:=", "Positive"
    ]
)

oModule.AssignCoilGroup(
    [
        "NAME:B-",
        "Objects:=", ["Coil_4", "Coil_10"],
        "Conductor number:=", "40",
        "PolarityType:=", "Negative"
    ]
)

oModule.AssignCoilGroup(
    [
        "NAME:C+",
        "Objects:=", ["Coil_5", "Coil_11"],
        "Conductor number:=", "40",
        "PolarityType:=", "Positive"
    ]
)

oModule.AssignCoilGroup(
    [
        "NAME:C-",
        "Objects:=", ["Coil_6", "Coil_12"],
        "Conductor number:=", "40",
        "PolarityType:=", "Negative"
    ]
)

# Step 3: 将 Coil Group 绑定到对应 Winding
oModule.AddWindingCoils("WindingA", ["A+", "A-"])
oModule.AddWindingCoils("WindingB", ["B+", "B-"])
oModule.AddWindingCoils("WindingC", ["C+", "C-"])

print("Winding assignment complete")
print(f"  Layout:  8p/12s, source=canonical")
print(f"  k_w:     0.8660")
print(f"  q:       0.500")
print(f"  Phase A: 2+ 2-")
print(f"  Phase B: 2+ 2-")
print(f"  Phase C: 2+ 2-")